# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '*/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Packages Docker Registry
        run: echo "${{ secrets.DOCKER_SECRET_KEY }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull docker image
        run: docker pull docker.pkg.github.com/manoj2210/cronjobnucleus/teams-issue-notifier:1.0
      
      - name: Run docker image
        run: docker run docker.pkg.github.com/manoj2210/cronjobnucleus/teams-issue-notifier:1.0  
